# Generated by Django 5.0.2 on 2024-05-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="description",
            field=models.CharField(default="Default description", max_length=400),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.CharField(default="Terry Davis", max_length=100),
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(default="Default content"),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(default="Default title", max_length=100),
        ),
    ]
